/**
 * Pure assembly of the generated TypeScript file. Kept free of any I/O so it
 * can be unit-tested directly. The command layer fetches the inputs (permission
 * codes, user/context JSON Schemas) and hands them here.
 */
import { schemaToNamedType, type JsonSchema } from "../../lib/json-schema-to-ts.js";

/** Fixed names of the generated declarations (documented in the README). */
export const TYPE_NAMES = {
  codes: "ArkveilCodes",
  user: "ArkveilUserAttributes",
  context: "ArkveilContextAttributes",
} as const;

export type GenerateInclude = "codes" | "user" | "context";

export interface AssembleInput {
  /** Permission codes (sorted, unique). Present when "codes" is included. */
  codes?: string[];
  /** User attribute JSON Schema. Present when "user" is included. */
  userSchema?: JsonSchema;
  /** Context attribute JSON Schema. Present when "context" is included. */
  contextSchema?: JsonSchema;
}

const HEADER = `// AUTO-GENERATED by \`arkveil generate typescript\`. Do not edit by hand.
//
// This file types the Arkveil SDK for TypeScript by declaration-merging into
// the \`arkveil\` package. Import it once (a side-effect import is enough) and
// permission codes plus \`user\` / \`context\` attributes become typed across
// \`checkPermission\`, the Node \`permissionPoint\` middleware, and the NestJS
// \`@PermissionPoint\` decorator. Regenerate whenever codes or schemas change.`;

function renderCodes(codes: string[]): string {
  if (codes.length === 0) {
    return `/** No permission codes were found in this project (falls back to \`string\`). */
export type ${TYPE_NAMES.codes} = string;`;
  }
  const union = codes.map((c) => `  | ${JSON.stringify(c)}`).join("\n");
  return `/** Union of every permission code defined in this Arkveil project. */
export type ${TYPE_NAMES.codes} =
${union};`;
}

/** Build the full generated TypeScript source. */
export function assembleTypeScript(input: AssembleInput): string {
  const blocks: string[] = [HEADER];
  const augment: string[] = [];

  if (input.codes !== undefined) {
    blocks.push(renderCodes(input.codes));
    augment.push(`  interface ArkveilCodeRegistry {\n    codes: ${TYPE_NAMES.codes};\n  }`);
  }

  if (input.userSchema !== undefined) {
    blocks.push(
      schemaToNamedType(
        TYPE_NAMES.user,
        input.userSchema,
        "Shape of `user` attributes (from `arkveil schemas get user`).",
      ),
    );
    augment.push(
      `  interface ArkveilUserRegistry {\n    attributes: ${TYPE_NAMES.user};\n  }`,
    );
  }

  if (input.contextSchema !== undefined) {
    blocks.push(
      schemaToNamedType(
        TYPE_NAMES.context,
        input.contextSchema,
        "Shape of `context` attributes (from `arkveil schemas get context`).",
      ),
    );
    augment.push(
      `  interface ArkveilContextRegistry {\n    attributes: ${TYPE_NAMES.context};\n  }`,
    );
  }

  blocks.push(
    `// Register the generated types globally so the default \`Arkveil\` generics
// pick them up automatically — no need to pass them everywhere.
declare module "arkveil" {
${augment.join("\n")}
}`,
  );

  return `${blocks.join("\n\n")}\n`;
}
